/*
 * jerryscript_esp32.h
 *
 *  Created on: Nov 13, 2016
 *      Author: kolban
 */

#ifndef COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_JERRYSCRIPT_ESP32_H_
#define COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_JERRYSCRIPT_ESP32_H_
void jerryscript_esp32_init();

#endif /* COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_JERRYSCRIPT_ESP32_H_ */
