/*
 * require.h
 *
 *  Created on: Nov 12, 2016
 *      Author: kolban
 */

#ifndef COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_REQUIRE_H_
#define COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_REQUIRE_H_
  void jerryscript_esp32_register_requires();

#endif /* COMPONENTS_JERRYSCRIPT_ESP32_INCLUDE_JERRYSCRIPT_ESP32_REQUIRE_H_ */
